import { CONVERSION_ENTRIES, FILE_LIMIT_MB } from "@/constants/app";
import type { ConversionTool, ToolDefinition } from "./types";

/**
 * The platform tool registry.
 *
 * Converters are *derived* from `CONVERSIONS` rather than re-declared, so the
 * existing catalog stays the single source of truth and the two can never
 * disagree. Non-converter tools are appended alongside them.
 */

/**
 * Format names map to stable lowercase tags. Only entries that need to differ
 * from `format.toLowerCase()` appear here.
 */
const FORMAT_TAG_OVERRIDES: Record<string, string> = {
  Text: "txt",
  "Markdown Table": "markdown",
};

function formatToTag(format: string): string {
  return FORMAT_TAG_OVERRIDES[format] ?? format.toLowerCase();
}

const conversionTools: ConversionTool[] = CONVERSION_ENTRIES.map(([type, conversion]) => ({
  kind: "file-conversion",
  slug: type,
  conversionType: type,
  name: `${conversion.fromFormat} to ${conversion.toFormat}`,
  summary: conversion.description,
  category: conversion.category,
  // Tags are derived so a new converter is taggable without a second edit.
  tags: Array.from(new Set([formatToTag(conversion.fromFormat), formatToTag(conversion.toFormat), "convert"])),
  href: `/conversion/${type}`,
  capabilities: {
    processing: "on-device",
    // Verified: no converter module performs a network request. Every heavy
    // dependency (jspdf, html2canvas, docx, mammoth) is bundled and imported
    // dynamically from the app itself.
    requiresNetwork: false,
    persistence: "none",
    maxFileSizeMb: FILE_LIMIT_MB,
  },
  conversion: {
    from: conversion.from,
    to: conversion.to,
    fromFormat: conversion.fromFormat,
    toFormat: conversion.toFormat,
    acceptedExtensions: conversion.acceptedExtensions,
    outputExtension: conversion.outputExtension,
  },
}));

/**
 * Tools that are not file conversions. These exist to prove the platform can
 * carry more than one interaction model; each declares its own capabilities.
 */
const utilityTools: ToolDefinition[] = [
  { kind: "text", slug: "json-to-yaml-text", name: "JSON to YAML Text", summary: "Convert JSON text into readable YAML directly in your browser.", category: "developer", tags: ["json", "yaml", "convert"], href: "/tools/json-to-yaml", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "yaml-to-json-text", name: "YAML to JSON Text", summary: "Convert YAML text into formatted JSON locally.", category: "developer", tags: ["yaml", "json", "convert"], href: "/tools/yaml-to-json", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "xml-formatter", name: "XML Formatter", summary: "Format XML with consistent indentation and readable structure.", category: "developer", tags: ["xml", "format", "code"], href: "/tools/xml-formatter", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "bmi-calculator", name: "BMI Calculator", summary: "Calculate body mass index from height and weight.", category: "calculators", tags: ["bmi", "health", "math"], href: "/tools/bmi-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "compound-interest", name: "Compound Interest Calculator", summary: "Estimate growth with principal, rate, time, and compounding frequency.", category: "calculators", tags: ["interest", "finance", "savings"], href: "/tools/compound-interest", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "json-validator", name: "JSON Validator", summary: "Check JSON syntax and get a clear validation result instantly.", category: "developer", tags: ["json", "validate", "debug"], href: "/tools/json-validator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "regex-tester", name: "Regex Tester", summary: "Test regular expressions against sample text with match details.", category: "developer", tags: ["regex", "text", "debug"], href: "/tools/regex-tester", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "text-diff", name: "Text Diff", summary: "Compare two pieces of text and quickly spot what changed.", category: "utilities", tags: ["text", "compare", "diff"], href: "/tools/text-diff", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "age-calculator", name: "Age Calculator", summary: "Calculate an exact age from a date of birth.", category: "calculators", tags: ["age", "date", "time"], href: "/tools/age-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "simple-interest", name: "Simple Interest Calculator", summary: "Calculate simple interest and the total amount from principal, rate, and time.", category: "calculators", tags: ["interest", "finance", "math"], href: "/tools/simple-interest", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },

  { kind: "calculator", slug: "random-number-generator", name: "Random Number Generator", summary: "Generate a random number between any minimum and maximum value.", category: "generators", tags: ["random", "number", "math"], href: "/tools/random-number-generator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "discount-calculator", name: "Discount Calculator", summary: "Calculate sale prices, savings, and final totals from a discount percentage.", category: "calculators", tags: ["discount", "percent", "money"], href: "/tools/discount-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "tip-calculator", name: "Tip Calculator", summary: "Split a bill and calculate a fair tip for any group size.", category: "calculators", tags: ["tip", "bill", "money"], href: "/tools/tip-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },

  {
    kind: "text", slug: "slug-generator", name: "Slug Generator", summary: "Turn titles and phrases into clean, URL-friendly slugs.", category: "utilities", tags: ["text", "url", "seo"], href: "/tools/slug-generator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "duplicate-line-remover", name: "Duplicate Line Remover", summary: "Remove repeated lines and clean up lists instantly in your browser.", category: "utilities", tags: ["text", "clean", "list"], href: "/tools/duplicate-line-remover", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "password-generator", name: "Password Generator", summary: "Create strong random passwords locally with configurable length and character sets.", category: "security", tags: ["password", "security", "random"], href: "/tools/password-generator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "json-formatter",
    name: "JSON Formatter",
    summary: "Format, validate and minify JSON without leaving the page.",
    category: "developer",
    tags: ["json", "format", "validate"],
    href: "/tools/json-formatter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Indent width and sort-keys are preferences, not content.
      persistence: "preferences",
    },
  },
  {
    kind: "text",
    slug: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    summary: "Encode text as Base64 or decode Base64 back to text, with full Unicode support.",
    category: "developer",
    tags: ["base64", "encode", "decode", "text"],
    href: "/tools/base64-encoder",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    summary: "Percent-encode text for URLs, or decode an encoded string back to plain text.",
    category: "web",
    tags: ["url", "encode", "decode", "percent"],
    href: "/tools/url-encoder",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "uuid-generator",
    name: "UUID Generator",
    summary: "Generate random RFC 4122 version 4 UUIDs in bulk, with formatting options.",
    category: "security",
    tags: ["uuid", "guid", "random", "id"],
    href: "/tools/uuid-generator",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Count and formatting options persist; generated values never do.
      persistence: "preferences",
    },
  },
  {
    kind: "text",
    slug: "jwt-decoder",
    name: "JWT Decoder",
    summary: "Inspect a JSON Web Token's header and payload with claim dates decoded. No verification.",
    category: "security",
    tags: ["jwt", "token", "json", "debug"],
    href: "/tools/jwt-decoder",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "word-counter",
    name: "Word Counter",
    summary: "Count words, characters, sentences and estimated reading time as you type.",
    category: "utilities",
    tags: ["text", "writing", "count"],
    href: "/tools/word-counter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "text-case-converter",
    name: "Text Case Converter",
    summary: "Convert text between upper, lower, title, sentence, camel, snake and more.",
    category: "utilities",
    tags: ["text", "case", "writing", "format"],
    href: "/tools/text-case-converter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // The last-used style persists; the text never does.
      persistence: "preferences",
    },
  },
  {
    kind: "timer",
    slug: "pomodoro",
    name: "Pomodoro Timer",
    summary: "Work in focused intervals with automatic short and long breaks.",
    category: "utilities",
    tags: ["time", "focus", "productivity"],
    href: "/tools/pomodoro",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Interval lengths persist; nothing about session content is stored.
      persistence: "preferences",
    },
  },
  {
    kind: "calculator",
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    summary: "Work out percentages of values, shares of a total, and percentage change.",
    category: "calculators",
    tags: ["percent", "math", "change"],
    href: "/tools/percentage-calculator",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "date-difference",
    name: "Date Difference Calculator",
    summary: "Measure the time between two dates in days, weeks, months and weekdays.",
    category: "calculators",
    tags: ["date", "time", "days"],
    href: "/tools/date-difference",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "unit-converter",
    name: "Unit Converter",
    summary: "Convert length, mass, temperature, volume, time and digital storage units instantly.",
    category: "calculators",
    tags: ["units", "convert", "length", "temperature", "math"],
    href: "/tools/unit-converter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "reading-time",
    name: "Reading Time Calculator",
    summary: "Estimate how long text takes to read or speak, with adjustable reading pace.",
    category: "utilities",
    tags: ["text", "reading", "writing", "time"],
    href: "/tools/reading-time",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "sql-formatter",
    name: "SQL Formatter",
    summary: "Format SQL queries for any major dialect with clean indentation and optional uppercase keywords.",
    category: "developer",
    tags: ["sql", "format", "code", "database"],
    href: "/tools/sql-formatter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Dialect and style choices persist; query text never does.
      persistence: "preferences",
    },
  },
  {
    kind: "text",
    slug: "html-formatter",
    name: "HTML Formatter",
    summary: "Pretty-print HTML with consistent indentation, right in your browser.",
    category: "developer",
    tags: ["html", "format", "code"],
    href: "/tools/html-formatter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "css-formatter",
    name: "CSS Formatter",
    summary: "Format CSS with readable indentation and one declaration per line.",
    category: "developer",
    tags: ["css", "format", "code"],
    href: "/tools/css-formatter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "js-formatter",
    name: "JavaScript Formatter",
    summary: "Format JavaScript with consistent indentation, locally.",
    category: "developer",
    tags: ["javascript", "format", "code"],
    href: "/tools/js-formatter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    summary: "Generate TypeScript types from a JSON sample, with named types for nested objects.",
    category: "developer",
    tags: ["json", "typescript", "code", "generate"],
    href: "/tools/json-to-typescript",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "find-replace",
    name: "Find and Replace",
    summary: "Search and replace text with optional regex, capture groups, and a live match count.",
    category: "utilities",
    tags: ["text", "replace", "regex", "clean"],
    href: "/tools/find-replace",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    summary: "Generate placeholder paragraphs, sentences or words for mockups and designs.",
    category: "utilities",
    tags: ["text", "writing", "filler", "generate"],
    href: "/tools/lorem-ipsum",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "hash-generator",
    name: "Hash Generator",
    summary: "Hash text or files with MD5, SHA-1, SHA-256, SHA-384 and SHA-512, entirely on-device.",
    category: "security",
    tags: ["hash", "md5", "sha", "security", "encode"],
    href: "/tools/hash-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "calculator",
    slug: "qr-code-generator",
    name: "QR Code Generator",
    summary: "Create QR codes for any text with size, color and error-correction control, downloadable as PNG or SVG.",
    category: "developer",
    tags: ["qr", "code", "generate", "image"],
    href: "/tools/qr-code-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "loan-calculator",
    name: "Loan / EMI Calculator",
    summary: "Compute monthly payments, total interest and a year-by-year amortization schedule.",
    category: "calculators",
    tags: ["loan", "emi", "interest", "finance", "mortgage"],
    href: "/tools/loan-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "color-converter",
    name: "Color Converter",
    summary: "Convert between HEX, RGB and HSL, with a live swatch and WCAG contrast ratios.",
    category: "developer",
    tags: ["color", "hex", "rgb", "hsl", "css", "design"],
    href: "/tools/color-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    summary: "Convert between Unix timestamps (seconds or milliseconds) and human-readable dates, both ways.",
    category: "calculators",
    tags: ["time", "unix", "timestamp", "date", "developer"],
    href: "/tools/unix-timestamp",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "timer",
    slug: "stopwatch",
    name: "Stopwatch",
    summary: "A fast, precise stopwatch with laps and splits, running entirely in your browser.",
    category: "utilities",
    tags: ["time", "stopwatch", "focus", "productivity"],
    href: "/tools/stopwatch",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "image-compressor",
    name: "Image Compressor",
    summary: "Compress PNG and JPG images with a quality slider, comparing before and after sizes.",
    category: "images",
    tags: ["image", "compress", "webp", "jpeg", "optimize"],
    href: "/tools/image-compressor",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "calculator",
    slug: "image-resizer",
    name: "Image Resizer",
    summary: "Resize images to exact dimensions or a target box, with aspect ratio preserved by default.",
    category: "images",
    tags: ["image", "resize", "dimensions", "scale"],
    href: "/tools/image-resizer",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "text",
    slug: "js-minifier",
    name: "JS Minifier",
    summary: "Minify JavaScript with real terser — comments, whitespace and identifiers — with ES5/ES6 target and console stripping.",
    category: "developer",
    tags: ["javascript", "minify", "compress", "code"],
    href: "/tools/js-minifier",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "css-minifier",
    name: "CSS Minifier",
    summary: "Strip comments, collapse whitespace, shorten hex colors and drop empty rules from CSS.",
    category: "developer",
    tags: ["css", "minify", "compress", "code"],
    href: "/tools/css-minifier",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "html-minifier",
    name: "HTML Minifier",
    summary: "Remove comments, normalize tag whitespace and collapse text whitespace — safely, around scripts, styles and textareas.",
    category: "developer",
    tags: ["html", "minify", "compress", "code"],
    href: "/tools/html-minifier",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "xml-validator",
    name: "XML Validator",
    summary: "Check XML well-formedness with the line and column of the first structural error.",
    category: "developer",
    tags: ["xml", "validate", "lint", "well-formed"],
    href: "/tools/xml-validator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "yaml-validator",
    name: "YAML Validator",
    summary: "Validate YAML documents — including multi-document streams — with line and column for errors.",
    category: "developer",
    tags: ["yaml", "validate", "lint"],
    href: "/tools/yaml-validator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "json-schema-validator",
    name: "JSON Schema Validator",
    summary: "Validate a JSON document against a JSON Schema (draft-07 plus common formats) and list every violation.",
    category: "developer",
    tags: ["json", "schema", "validate", "ajv"],
    href: "/tools/json-schema-validator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "html-entities",
    name: "HTML Entity Encoder/Decoder",
    summary: "Encode text as HTML entities (named or numeric) or decode an entity-laden string back to plain text.",
    category: "developer",
    tags: ["html", "entities", "encode", "decode"],
    href: "/tools/html-entities",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "unicode-escapes",
    name: "Unicode Escapes",
    summary: "Convert text to \\uXXXX escapes and back, with a code-point breakdown of every character used.",
    category: "developer",
    tags: ["unicode", "escape", "encode", "text"],
    href: "/tools/unicode-escapes",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "ip-cidr-calculator",
    name: "IP & CIDR Calculator",
    summary: "Analyze IPv4 and IPv6 addresses: network, broadcast, usable hosts and block size from a CIDR.",
    category: "developer",
    tags: ["ip", "cidr", "network", "subnet"],
    href: "/tools/ip-cidr-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "url-parser",
    name: "URL Parser",
    summary: "Break any URL into protocol, host, port, path, query parameters and hash — entirely on-device.",
    category: "web",
    tags: ["url", "parse", "query", "web"],
    href: "/tools/url-parser",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "query-string-builder",
    name: "Query String Builder",
    summary: "Build clean URL query strings from key/value pairs, with sorting, encoding and empty-pair handling.",
    category: "web",
    tags: ["query", "url", "builder", "web"],
    href: "/tools/query-string-builder",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "utm-builder",
    name: "UTM Builder & Parser",
    summary: "Tag campaign URLs with utm_* parameters, or inspect which UTM tags an existing URL carries.",
    category: "web",
    tags: ["utm", "campaign", "url", "marketing"],
    href: "/tools/utm-builder",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "robots-txt-analyzer",
    name: "robots.txt Analyzer",
    summary: "Paste a robots.txt and check exactly what any user agent may fetch, with the matching rules explained.",
    category: "web",
    tags: ["robots", "crawlers", "seo", "web"],
    href: "/tools/robots-txt-analyzer",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    summary: "Generate harmonious five-color palettes — analogous, complementary, triadic and more — from a base color.",
    category: "generators",
    tags: ["color", "palette", "design", "harmony"],
    href: "/tools/color-palette-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    summary: "Compose linear, radial and conic CSS gradients with editable color stops and a live preview.",
    category: "generators",
    tags: ["css", "gradient", "design"],
    href: "/tools/css-gradient-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "mock-data-generator",
    name: "Mock Data Generator",
    summary: "Generate deterministic fake rows — names, emails, companies, amounts — as CSV or JSON.",
    category: "generators",
    tags: ["mock", "data", "fake", "test"],
    href: "/tools/mock-data-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "barcode-generator",
    name: "Barcode Generator",
    summary: "Render Code 128, Code 39, EAN-13, EAN-8 and ITF-14 barcodes as scalable SVG, downloadable as SVG or PNG.",
    category: "generators",
    tags: ["barcode", "code128", "ean", "labels"],
    href: "/tools/barcode-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "investment-calculator",
    name: "Investment Calculator",
    summary: "Forecast growth from an initial deposit plus monthly contributions, compounded monthly, with a year-by-year table.",
    category: "calculators",
    tags: ["investment", "compound", "savings", "finance"],
    href: "/tools/investment-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "roi-calculator",
    name: "ROI Calculator",
    summary: "Return on investment: profit, percentage return and multiple from what you put in and got back.",
    category: "calculators",
    tags: ["roi", "return", "profit", "finance"],
    href: "/tools/roi-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "cagr-calculator",
    name: "CAGR Calculator",
    summary: "Compound annual growth rate from a start value, an end value and a number of years.",
    category: "calculators",
    tags: ["cagr", "growth", "compound", "finance"],
    href: "/tools/cagr-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "ratio-calculator",
    name: "Ratio Calculator",
    summary: "Simplify any ratio to its lowest terms and see each side's share of the whole.",
    category: "calculators",
    tags: ["ratio", "simplify", "proportion", "math"],
    href: "/tools/ratio-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "statistics-calculator",
    name: "Statistics Calculator",
    summary: "Mean, median, mode, min/max, range, variance and standard deviation for a list of numbers.",
    category: "calculators",
    tags: ["statistics", "mean", "median", "stddev"],
    href: "/tools/statistics-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "word-frequency",
    name: "Word Frequency Counter",
    summary: "Rank the most common words in any text with counts, shares and a top-N list.",
    category: "utilities",
    tags: ["words", "frequency", "text", "count"],
    href: "/tools/word-frequency",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "line-sorter",
    name: "Line Sorter & Cleaner",
    summary: "Sort lines alphabetically or naturally, remove duplicates and blank lines, and trim each line.",
    category: "utilities",
    tags: ["sort", "lines", "text", "clean"],
    href: "/tools/line-sorter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "markdown-previewer",
    name: "Markdown Previewer",
    summary: "Write Markdown and see the rendered result live, with links, code, tables and more.",
    category: "utilities",
    tags: ["markdown", "preview", "render", "writing"],
    href: "/tools/markdown-previewer",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
];

export const TOOLS: readonly ToolDefinition[] = [...conversionTools, ...utilityTools];

const TOOLS_BY_SLUG = new Map(TOOLS.map((tool) => [tool.slug, tool]));

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS_BY_SLUG.get(slug);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === category);
}

/** All tags in use, sorted, for building filter UI without hard-coding a list. */
export function getAllTags(): string[] {
  return Array.from(new Set(TOOLS.flatMap((tool) => tool.tags))).sort();
}
