import { CONVERSION_ENTRIES, FILE_LIMIT_MB } from "@/constants/app";
import type { ConversionTool, ToolDefinition } from "./types";

/**
 * The platform tool registry.
 *
 * Converters are *derived* from `CONVERSIONS` rather than re-declared, so the
 * existing catalog stays the single source of truth and the two can never
 * disagree. Non-converter tools are appended alongside them.
 */

/**
 * Format names map to stable lowercase tags. Only entries that need to differ
 * from `format.toLowerCase()` appear here.
 */
const FORMAT_TAG_OVERRIDES: Record<string, string> = {
  Text: "txt",
  "Markdown Table": "markdown",
};

function formatToTag(format: string): string {
  return FORMAT_TAG_OVERRIDES[format] ?? format.toLowerCase();
}

const conversionTools: ConversionTool[] = CONVERSION_ENTRIES.map(([type, conversion]) => ({
  kind: "file-conversion",
  slug: type,
  conversionType: type,
  name: `${conversion.fromFormat} to ${conversion.toFormat}`,
  summary: conversion.description,
  category: conversion.category,
  // Tags are derived so a new converter is taggable without a second edit.
  tags: Array.from(new Set([formatToTag(conversion.fromFormat), formatToTag(conversion.toFormat), "convert"])),
  href: `/conversion/${type}`,
  capabilities: {
    processing: "on-device",
    // Verified: no converter module performs a network request. Every heavy
    // dependency (jspdf, html2canvas, docx, mammoth) is bundled and imported
    // dynamically from the app itself.
    requiresNetwork: false,
    persistence: "none",
    maxFileSizeMb: FILE_LIMIT_MB,
  },
  conversion: {
    from: conversion.from,
    to: conversion.to,
    fromFormat: conversion.fromFormat,
    toFormat: conversion.toFormat,
    acceptedExtensions: conversion.acceptedExtensions,
    outputExtension: conversion.outputExtension,
  },
}));

/**
 * Tools that are not file conversions. These exist to prove the platform can
 * carry more than one interaction model; each declares its own capabilities.
 */
const utilityTools: ToolDefinition[] = [
  { kind: "text", slug: "json-to-yaml-text", name: "JSON to YAML Text", summary: "Convert JSON text into readable YAML directly in your browser.", category: "developer", tags: ["json", "yaml", "convert"], href: "/tools/json-to-yaml", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "yaml-to-json-text", name: "YAML to JSON Text", summary: "Convert YAML text into formatted JSON locally.", category: "developer", tags: ["yaml", "json", "convert"], href: "/tools/yaml-to-json", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "xml-formatter", name: "XML Formatter", summary: "Format XML with consistent indentation and readable structure.", category: "developer", tags: ["xml", "format", "code"], href: "/tools/xml-formatter", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "bmi-calculator", name: "BMI Calculator", summary: "Calculate body mass index from height and weight.", category: "calculators", tags: ["bmi", "health", "math"], href: "/tools/bmi-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "compound-interest", name: "Compound Interest Calculator", summary: "Estimate growth with principal, rate, time, and compounding frequency.", category: "calculators", tags: ["interest", "finance", "savings"], href: "/tools/compound-interest", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "json-validator", name: "JSON Validator", summary: "Check JSON syntax and get a clear validation result instantly.", category: "developer", tags: ["json", "validate", "debug"], href: "/tools/json-validator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "regex-tester", name: "Regex Tester", summary: "Test regular expressions against sample text with match details.", category: "developer", tags: ["regex", "text", "debug"], href: "/tools/regex-tester", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "text", slug: "text-diff", name: "Text Diff", summary: "Compare two pieces of text and quickly spot what changed.", category: "utilities", tags: ["text", "compare", "diff"], href: "/tools/text-diff", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "age-calculator", name: "Age Calculator", summary: "Calculate an exact age from a date of birth.", category: "calculators", tags: ["age", "date", "time"], href: "/tools/age-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "simple-interest", name: "Simple Interest Calculator", summary: "Calculate simple interest and the total amount from principal, rate, and time.", category: "calculators", tags: ["interest", "finance", "math"], href: "/tools/simple-interest", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },

  { kind: "calculator", slug: "random-number-generator", name: "Random Number Generator", summary: "Generate a random number between any minimum and maximum value.", category: "generators", tags: ["random", "number", "math"], href: "/tools/random-number-generator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "discount-calculator", name: "Discount Calculator", summary: "Calculate sale prices, savings, and final totals from a discount percentage.", category: "calculators", tags: ["discount", "percent", "money"], href: "/tools/discount-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },
  { kind: "calculator", slug: "tip-calculator", name: "Tip Calculator", summary: "Split a bill and calculate a fair tip for any group size.", category: "calculators", tags: ["tip", "bill", "money"], href: "/tools/tip-calculator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" } },

  {
    kind: "text", slug: "slug-generator", name: "Slug Generator", summary: "Turn titles and phrases into clean, URL-friendly slugs.", category: "utilities", tags: ["text", "url", "seo"], href: "/tools/slug-generator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "duplicate-line-remover", name: "Duplicate Line Remover", summary: "Remove repeated lines and clean up lists instantly in your browser.", category: "utilities", tags: ["text", "clean", "list"], href: "/tools/duplicate-line-remover", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "password-generator", name: "Password Generator", summary: "Create strong random passwords locally with configurable length and character sets.", category: "security", tags: ["password", "security", "random"], href: "/tools/password-generator", capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "json-formatter",
    name: "JSON Formatter",
    summary: "Format, validate and minify JSON without leaving the page.",
    category: "developer",
    tags: ["json", "format", "validate"],
    href: "/tools/json-formatter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Indent width and sort-keys are preferences, not content.
      persistence: "preferences",
    },
  },
  {
    kind: "text",
    slug: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    summary: "Encode text as Base64 or decode Base64 back to text, with full Unicode support.",
    category: "developer",
    tags: ["base64", "encode", "decode", "text"],
    href: "/tools/base64-encoder",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    summary: "Percent-encode text for URLs, or decode an encoded string back to plain text.",
    category: "web",
    tags: ["url", "encode", "decode", "percent"],
    href: "/tools/url-encoder",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "uuid-generator",
    name: "UUID Generator",
    summary: "Generate random RFC 4122 version 4 UUIDs in bulk, with formatting options.",
    category: "security",
    tags: ["uuid", "guid", "random", "id"],
    href: "/tools/uuid-generator",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Count and formatting options persist; generated values never do.
      persistence: "preferences",
    },
  },
  {
    kind: "text",
    slug: "jwt-decoder",
    name: "JWT Decoder",
    summary: "Inspect a JSON Web Token's header and payload with claim dates decoded. No verification.",
    category: "security",
    tags: ["jwt", "token", "json", "debug"],
    href: "/tools/jwt-decoder",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "word-counter",
    name: "Word Counter",
    summary: "Count words, characters, sentences and estimated reading time as you type.",
    category: "utilities",
    tags: ["text", "writing", "count"],
    href: "/tools/word-counter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "text-case-converter",
    name: "Text Case Converter",
    summary: "Convert text between upper, lower, title, sentence, camel, snake and more.",
    category: "utilities",
    tags: ["text", "case", "writing", "format"],
    href: "/tools/text-case-converter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // The last-used style persists; the text never does.
      persistence: "preferences",
    },
  },
  {
    kind: "timer",
    slug: "pomodoro",
    name: "Pomodoro Timer",
    summary: "Work in focused intervals with automatic short and long breaks.",
    category: "utilities",
    tags: ["time", "focus", "productivity"],
    href: "/tools/pomodoro",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Interval lengths persist; nothing about session content is stored.
      persistence: "preferences",
    },
  },
  {
    kind: "calculator",
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    summary: "Work out percentages of values, shares of a total, and percentage change.",
    category: "calculators",
    tags: ["percent", "math", "change"],
    href: "/tools/percentage-calculator",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "date-difference",
    name: "Date Difference Calculator",
    summary: "Measure the time between two dates in days, weeks, months and weekdays.",
    category: "calculators",
    tags: ["date", "time", "days"],
    href: "/tools/date-difference",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "unit-converter",
    name: "Unit Converter",
    summary: "Convert length, mass, temperature, volume, time and digital storage units instantly.",
    category: "calculators",
    tags: ["units", "convert", "length", "temperature", "math"],
    href: "/tools/unit-converter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "calculator",
    slug: "reading-time",
    name: "Reading Time Calculator",
    summary: "Estimate how long text takes to read or speak, with adjustable reading pace.",
    category: "utilities",
    tags: ["text", "reading", "writing", "time"],
    href: "/tools/reading-time",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      persistence: "none",
    },
  },
  {
    kind: "text",
    slug: "sql-formatter",
    name: "SQL Formatter",
    summary: "Format SQL queries for any major dialect with clean indentation and optional uppercase keywords.",
    category: "developer",
    tags: ["sql", "format", "code", "database"],
    href: "/tools/sql-formatter",
    capabilities: {
      processing: "on-device",
      requiresNetwork: false,
      // Dialect and style choices persist; query text never does.
      persistence: "preferences",
    },
  },
  {
    kind: "text",
    slug: "html-formatter",
    name: "HTML Formatter",
    summary: "Pretty-print HTML with consistent indentation, right in your browser.",
    category: "developer",
    tags: ["html", "format", "code"],
    href: "/tools/html-formatter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "css-formatter",
    name: "CSS Formatter",
    summary: "Format CSS with readable indentation and one declaration per line.",
    category: "developer",
    tags: ["css", "format", "code"],
    href: "/tools/css-formatter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "js-formatter",
    name: "JavaScript Formatter",
    summary: "Format JavaScript with consistent indentation, locally.",
    category: "developer",
    tags: ["javascript", "format", "code"],
    href: "/tools/js-formatter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    summary: "Generate TypeScript types from a JSON sample, with named types for nested objects.",
    category: "developer",
    tags: ["json", "typescript", "code", "generate"],
    href: "/tools/json-to-typescript",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "find-replace",
    name: "Find and Replace",
    summary: "Search and replace text with optional regex, capture groups, and a live match count.",
    category: "utilities",
    tags: ["text", "replace", "regex", "clean"],
    href: "/tools/find-replace",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    summary: "Generate placeholder paragraphs, sentences or words for mockups and designs.",
    category: "utilities",
    tags: ["text", "writing", "filler", "generate"],
    href: "/tools/lorem-ipsum",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "hash-generator",
    name: "Hash Generator",
    summary: "Hash text or files with MD5, SHA-1, SHA-256, SHA-384 and SHA-512, entirely on-device.",
    category: "security",
    tags: ["hash", "md5", "sha", "security", "encode"],
    href: "/tools/hash-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "calculator",
    slug: "qr-code-generator",
    name: "QR Code Generator",
    summary: "Create QR codes for any text with size, color and error-correction control, downloadable as PNG or SVG.",
    category: "developer",
    tags: ["qr", "code", "generate", "image"],
    href: "/tools/qr-code-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "loan-calculator",
    name: "Loan / EMI Calculator",
    summary: "Compute monthly payments, total interest and a year-by-year amortization schedule.",
    category: "calculators",
    tags: ["loan", "emi", "interest", "finance", "mortgage"],
    href: "/tools/loan-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "color-converter",
    name: "Color Converter",
    summary: "Convert between HEX, RGB and HSL, with a live swatch and WCAG contrast ratios.",
    category: "developer",
    tags: ["color", "hex", "rgb", "hsl", "css", "design"],
    href: "/tools/color-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    summary: "Convert between Unix timestamps (seconds or milliseconds) and human-readable dates, both ways.",
    category: "calculators",
    tags: ["time", "unix", "timestamp", "date", "developer"],
    href: "/tools/unix-timestamp",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "timer",
    slug: "stopwatch",
    name: "Stopwatch",
    summary: "A fast, precise stopwatch with laps and splits, running entirely in your browser.",
    category: "utilities",
    tags: ["time", "stopwatch", "focus", "productivity"],
    href: "/tools/stopwatch",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "image-compressor",
    name: "Image Compressor",
    summary: "Compress PNG and JPG images with a quality slider, comparing before and after sizes.",
    category: "images",
    tags: ["image", "compress", "webp", "jpeg", "optimize"],
    href: "/tools/image-compressor",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "calculator",
    slug: "image-resizer",
    name: "Image Resizer",
    summary: "Resize images to exact dimensions or a target box, with aspect ratio preserved by default.",
    category: "images",
    tags: ["image", "resize", "dimensions", "scale"],
    href: "/tools/image-resizer",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "text",
    slug: "js-minifier",
    name: "JS Minifier",
    summary: "Minify JavaScript with real terser — comments, whitespace and identifiers — with ES5/ES6 target and console stripping.",
    category: "developer",
    tags: ["javascript", "minify", "compress", "code"],
    href: "/tools/js-minifier",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "css-minifier",
    name: "CSS Minifier",
    summary: "Strip comments, collapse whitespace, shorten hex colors and drop empty rules from CSS.",
    category: "developer",
    tags: ["css", "minify", "compress", "code"],
    href: "/tools/css-minifier",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "html-minifier",
    name: "HTML Minifier",
    summary: "Remove comments, normalize tag whitespace and collapse text whitespace — safely, around scripts, styles and textareas.",
    category: "developer",
    tags: ["html", "minify", "compress", "code"],
    href: "/tools/html-minifier",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "xml-validator",
    name: "XML Validator",
    summary: "Check XML well-formedness with the line and column of the first structural error.",
    category: "developer",
    tags: ["xml", "validate", "lint", "well-formed"],
    href: "/tools/xml-validator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "yaml-validator",
    name: "YAML Validator",
    summary: "Validate YAML documents — including multi-document streams — with line and column for errors.",
    category: "developer",
    tags: ["yaml", "validate", "lint"],
    href: "/tools/yaml-validator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "json-schema-validator",
    name: "JSON Schema Validator",
    summary: "Validate a JSON document against a JSON Schema (draft-07 plus common formats) and list every violation.",
    category: "developer",
    tags: ["json", "schema", "validate", "ajv"],
    href: "/tools/json-schema-validator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "html-entities",
    name: "HTML Entity Encoder/Decoder",
    summary: "Encode text as HTML entities (named or numeric) or decode an entity-laden string back to plain text.",
    category: "developer",
    tags: ["html", "entities", "encode", "decode"],
    href: "/tools/html-entities",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "unicode-escapes",
    name: "Unicode Escapes",
    summary: "Convert text to \\uXXXX escapes and back, with a code-point breakdown of every character used.",
    category: "developer",
    tags: ["unicode", "escape", "encode", "text"],
    href: "/tools/unicode-escapes",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "ip-cidr-calculator",
    name: "IP & CIDR Calculator",
    summary: "Analyze IPv4 and IPv6 addresses: network, broadcast, usable hosts and block size from a CIDR.",
    category: "developer",
    tags: ["ip", "cidr", "network", "subnet"],
    href: "/tools/ip-cidr-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "url-parser",
    name: "URL Parser",
    summary: "Break any URL into protocol, host, port, path, query parameters and hash — entirely on-device.",
    category: "web",
    tags: ["url", "parse", "query", "web"],
    href: "/tools/url-parser",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "query-string-builder",
    name: "Query String Builder",
    summary: "Build clean URL query strings from key/value pairs, with sorting, encoding and empty-pair handling.",
    category: "web",
    tags: ["query", "url", "builder", "web"],
    href: "/tools/query-string-builder",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "utm-builder",
    name: "UTM Builder & Parser",
    summary: "Tag campaign URLs with utm_* parameters, or inspect which UTM tags an existing URL carries.",
    category: "web",
    tags: ["utm", "campaign", "url", "marketing"],
    href: "/tools/utm-builder",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "robots-txt-analyzer",
    name: "robots.txt Analyzer",
    summary: "Paste a robots.txt and check exactly what any user agent may fetch, with the matching rules explained.",
    category: "web",
    tags: ["robots", "crawlers", "seo", "web"],
    href: "/tools/robots-txt-analyzer",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    summary: "Generate harmonious five-color palettes — analogous, complementary, triadic and more — from a base color.",
    category: "generators",
    tags: ["color", "palette", "design", "harmony"],
    href: "/tools/color-palette-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "css-gradient-generator",
    name: "CSS Gradient Generator",
    summary: "Compose linear, radial and conic CSS gradients with editable color stops and a live preview.",
    category: "generators",
    tags: ["css", "gradient", "design"],
    href: "/tools/css-gradient-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "mock-data-generator",
    name: "Mock Data Generator",
    summary: "Generate deterministic fake rows — names, emails, companies, amounts — as CSV or JSON.",
    category: "generators",
    tags: ["mock", "data", "fake", "test"],
    href: "/tools/mock-data-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "barcode-generator",
    name: "Barcode Generator",
    summary: "Render Code 128, Code 39, EAN-13, EAN-8 and ITF-14 barcodes as scalable SVG, downloadable as SVG or PNG.",
    category: "generators",
    tags: ["barcode", "code128", "ean", "labels"],
    href: "/tools/barcode-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "investment-calculator",
    name: "Investment Calculator",
    summary: "Forecast growth from an initial deposit plus monthly contributions, compounded monthly, with a year-by-year table.",
    category: "calculators",
    tags: ["investment", "compound", "savings", "finance"],
    href: "/tools/investment-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator",
    slug: "roi-calculator",
    name: "ROI Calculator",
    summary: "Return on investment: profit, percentage return and multiple from what you put in and got back.",
    category: "calculators",
    tags: ["roi", "return", "profit", "finance"],
    href: "/tools/roi-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "cagr-calculator",
    name: "CAGR Calculator",
    summary: "Compound annual growth rate from a start value, an end value and a number of years.",
    category: "calculators",
    tags: ["cagr", "growth", "compound", "finance"],
    href: "/tools/cagr-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "ratio-calculator",
    name: "Ratio Calculator",
    summary: "Simplify any ratio to its lowest terms and see each side's share of the whole.",
    category: "calculators",
    tags: ["ratio", "simplify", "proportion", "math"],
    href: "/tools/ratio-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator",
    slug: "statistics-calculator",
    name: "Statistics Calculator",
    summary: "Mean, median, mode, min/max, range, variance and standard deviation for a list of numbers.",
    category: "calculators",
    tags: ["statistics", "mean", "median", "stddev"],
    href: "/tools/statistics-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "word-frequency",
    name: "Word Frequency Counter",
    summary: "Rank the most common words in any text with counts, shares and a top-N list.",
    category: "utilities",
    tags: ["words", "frequency", "text", "count"],
    href: "/tools/word-frequency",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text",
    slug: "line-sorter",
    name: "Line Sorter & Cleaner",
    summary: "Sort lines alphabetically or naturally, remove duplicates and blank lines, and trim each line.",
    category: "utilities",
    tags: ["sort", "lines", "text", "clean"],
    href: "/tools/line-sorter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text",
    slug: "markdown-previewer",
    name: "Markdown Previewer",
    summary: "Write Markdown and see the rendered result live, with links, code, tables and more.",
    category: "utilities",
    tags: ["markdown", "preview", "render", "writing"],
    href: "/tools/markdown-previewer",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  // ── Stage 3 tools (100 → 126) ──────────────────────────────────────
  {
    kind: "calculator", slug: "box-shadow-generator", name: "Box-Shadow Generator",
    summary: "Compose CSS box-shadow values with live preview, sliders and a one-click copy.",
    category: "generators", tags: ["css", "shadow", "design", "generator"],
    href: "/tools/box-shadow-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "dice-roller", name: "Dice Roller",
    summary: "Roll any number of dice with configurable sides (d4–d100), animated results and history.",
    category: "generators", tags: ["dice", "random", "rpg", "game"],
    href: "/tools/dice-roller",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "coin-flip", name: "Coin Flip",
    summary: "Flip a coin with animated results, streak tracking and a heads/tails history.",
    category: "generators", tags: ["coin", "random", "flip", "game"],
    href: "/tools/coin-flip",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "random-picker", name: "Random Picker",
    summary: "Pick randomly from a list of options — add, remove and reorder with optional no-repeat mode.",
    category: "generators", tags: ["random", "picker", "choose", "decide"],
    href: "/tools/random-picker",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "pdf-merge", name: "PDF Merge",
    summary: "Combine multiple PDF files into a single document, with reorderable page order.",
    category: "documents", tags: ["pdf", "merge", "combine", "files"],
    href: "/tools/pdf-merge",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "text", slug: "pdf-split", name: "PDF Split",
    summary: "Extract specific pages or split every page into its own PDF, downloaded as a ZIP.",
    category: "documents", tags: ["pdf", "split", "extract", "pages"],
    href: "/tools/pdf-split",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "calculator", slug: "image-cropper", name: "Image Cropper",
    summary: "Crop images with a draggable selection overlay — adjust position and size, then download.",
    category: "images", tags: ["image", "crop", "edit", "photo"],
    href: "/tools/image-cropper",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "calculator", slug: "image-color-picker", name: "Image Color Picker",
    summary: "Click any pixel in an image to pick its color — get HEX and RGB values with one-click copy.",
    category: "images", tags: ["image", "color", "picker", "hex", "design"],
    href: "/tools/image-color-picker",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "calculator", slug: "image-dimensions", name: "Image Dimensions Checker",
    summary: "Upload any image to see its width, height, aspect ratio, megapixels and file size.",
    category: "images", tags: ["image", "dimensions", "size", "aspect", "resolution"],
    href: "/tools/image-dimensions",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "text", slug: "image-to-base64", name: "Image to Base64",
    summary: "Convert any image to a Base64 data URI or raw Base64 string for embedding in code.",
    category: "images", tags: ["image", "base64", "encode", "data-uri"],
    href: "/tools/image-to-base64",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
  {
    kind: "text", slug: "json-to-python", name: "JSON to Python",
    summary: "Generate Python dataclass definitions from a JSON sample with correct type annotations.",
    category: "developer", tags: ["json", "python", "dataclass", "code"],
    href: "/tools/json-to-python",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "json-to-go", name: "JSON to Go",
    summary: "Generate Go struct definitions from a JSON sample with correct types and JSON tags.",
    category: "developer", tags: ["json", "go", "struct", "code"],
    href: "/tools/json-to-go",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "json-to-csharp", name: "JSON to C#",
    summary: "Generate C# class definitions from a JSON sample with auto-properties.",
    category: "developer", tags: ["json", "csharp", "class", "code", "dotnet"],
    href: "/tools/json-to-csharp",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "json-to-java", name: "JSON to Java",
    summary: "Generate Java class definitions from a JSON sample with getters, setters and typed fields.",
    category: "developer", tags: ["json", "java", "class", "code"],
    href: "/tools/json-to-java",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "json-to-sql", name: "JSON to SQL",
    summary: "Generate CREATE TABLE SQL statements from a JSON sample with appropriate column types.",
    category: "developer", tags: ["json", "sql", "database", "schema", "code"],
    href: "/tools/json-to-sql",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "cron-generator", name: "Cron Generator & Explainer",
    summary: "Build cron expressions with sliders and presets, and get a plain-English explanation.",
    category: "developer", tags: ["cron", "schedule", "job", "linux", "generator"],
    href: "/tools/cron-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "http-status-lookup", name: "HTTP Status Code Lookup",
    summary: "Search HTTP status codes by number or name — get a clear explanation for every code.",
    category: "developer", tags: ["http", "status", "code", "web", "api", "lookup"],
    href: "/tools/http-status-lookup",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "mime-type-lookup", name: "MIME Type Lookup",
    summary: "Search MIME types by name, extension or category — get the correct Content-Type value.",
    category: "developer", tags: ["mime", "type", "content-type", "web", "lookup"],
    href: "/tools/mime-type-lookup",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "user-agent-parser", name: "User-Agent Parser",
    summary: "Parse any User-Agent string to extract browser, engine, OS, device type and bot detection.",
    category: "developer", tags: ["user-agent", "browser", "parse", "web", "debug"],
    href: "/tools/user-agent-parser",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "mortgage-calculator", name: "Mortgage Calculator",
    summary: "Calculate monthly payments, total interest and a year-by-year amortization schedule.",
    category: "calculators", tags: ["mortgage", "loan", "interest", "finance", "home"],
    href: "/tools/mortgage-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "break-even-calculator", name: "Break-Even Calculator",
    summary: "Find how many units you need to sell to cover costs and hit a target profit.",
    category: "calculators", tags: ["break-even", "business", "profit", "cost", "finance"],
    href: "/tools/break-even-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "tax-calculator", name: "Tax Calculator",
    summary: "Estimate US federal and state income tax with bracket breakdown and effective rate.",
    category: "calculators", tags: ["tax", "income", "federal", "finance", "salary"],
    href: "/tools/tax-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "salary-calculator", name: "Salary Calculator",
    summary: "Convert annual salary to hourly, daily, weekly and monthly rates with optional tax deduction.",
    category: "calculators", tags: ["salary", "pay", "hourly", "income", "finance"],
    href: "/tools/salary-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "business-days-calculator", name: "Business Days Calculator",
    summary: "Count business days between dates or add business days to a start date.",
    category: "calculators", tags: ["business", "days", "workdays", "date", "calendar"],
    href: "/tools/business-days-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "timer", slug: "countdown-timer", name: "Countdown Timer & Stopwatch",
    summary: "Set a countdown with hours, minutes and seconds, or use the stopwatch with laps.",
    category: "utilities", tags: ["timer", "countdown", "stopwatch", "time"],
    href: "/tools/countdown-timer",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "meeting-time-converter", name: "Meeting Time Converter",
    summary: "Convert a meeting time across 17+ timezones — pick your timezone and see the world clock.",
    category: "utilities", tags: ["meeting", "time", "timezone", "world", "clock"],
    href: "/tools/meeting-time-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  // ── Stage 3b tools (126 → 150) ─────────────────────────────────────
  {
    kind: "text", slug: "json-diff", name: "JSON Diff",
    summary: "Compare two JSON objects and see every added, removed and changed field.",
    category: "developer", tags: ["json", "diff", "compare", "debug"],
    href: "/tools/json-diff",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "jwt-encoder", name: "JWT Encoder",
    summary: "Encode header and payload into a JWT structure with Base64URL encoding.",
    category: "security", tags: ["jwt", "token", "encode", "auth"],
    href: "/tools/jwt-encoder",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "html-to-jsx", name: "HTML to JSX",
    summary: "Convert HTML to React-compatible JSX — classes, styles, self-closing tags.",
    category: "developer", tags: ["html", "jsx", "react", "convert"],
    href: "/tools/html-to-jsx",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "css-units-converter", name: "CSS Units Converter",
    summary: "Convert between px, rem, em, pt, vh, vw and % for responsive CSS.",
    category: "developer", tags: ["css", "units", "px", "rem", "convert"],
    href: "/tools/css-units-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text", slug: "regex-cheatsheet", name: "Regex Cheatsheet & Tester",
    summary: "Common regex patterns with a syntax reference — test them against your text.",
    category: "developer", tags: ["regex", "pattern", "reference", "test"],
    href: "/tools/regex-cheatsheet",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "keyboard-keycode-tester", name: "Keyboard Key Code Tester",
    summary: "Press any key to see its key, code, keyCode, which, location and modifier state.",
    category: "developer", tags: ["keyboard", "keycode", "event", "debug"],
    href: "/tools/keyboard-keycode-tester",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "csv-column-extractor", name: "CSV Column Extractor",
    summary: "Select specific columns from CSV data by index — reorder, filter and export.",
    category: "developer", tags: ["csv", "column", "extract", "data"],
    href: "/tools/csv-column-extractor",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "aspect-ratio-calculator", name: "Aspect Ratio Calculator",
    summary: "Find the aspect ratio of any dimensions, or scale to a target ratio.",
    category: "calculators", tags: ["ratio", "aspect", "dimensions", "scale"],
    href: "/tools/aspect-ratio-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "fuel-cost-calculator", name: "Fuel Cost Calculator",
    summary: "Calculate trip fuel cost from distance, efficiency and fuel price.",
    category: "calculators", tags: ["fuel", "gas", "cost", "trip", "driving"],
    href: "/tools/fuel-cost-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "retirement-calculator", name: "Retirement Calculator",
    summary: "Project retirement savings with contributions, compound growth and inflation.",
    category: "calculators", tags: ["retirement", "savings", "compound", "finance", "invest"],
    href: "/tools/retirement-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator", slug: "pregnancy-due-date-calculator", name: "Pregnancy Due Date Calculator",
    summary: "Estimate a due date, current trimester and conception date from LMP.",
    category: "calculators", tags: ["pregnancy", "due date", "baby", "health", "date"],
    href: "/tools/pregnancy-due-date-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "gpa-calculator", name: "GPA Calculator",
    summary: "Calculate cumulative GPA from course grades and credit hours.",
    category: "calculators", tags: ["gpa", "grades", "school", "college", "calculator"],
    href: "/tools/gpa-calculator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "number-to-words", name: "Number to Words",
    summary: "Convert any integer to its English word representation.",
    category: "utilities", tags: ["number", "words", "convert", "text"],
    href: "/tools/number-to-words",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "data-size-converter", name: "Data Size Converter",
    summary: "Convert between bytes, KB, MB, GB, TB, PB and EB.",
    category: "calculators", tags: ["data", "size", "bytes", "convert", "storage"],
    href: "/tools/data-size-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "font-size-converter", name: "Font Size Converter",
    summary: "Convert between px, pt, rem, em, % and viewport units for web typography.",
    category: "developer", tags: ["font", "size", "px", "rem", "css", "typography"],
    href: "/tools/font-size-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "calculator", slug: "favicon-generator", name: "Favicon Generator",
    summary: "Create a simple favicon from text — choose colors, shape and size, download PNG.",
    category: "generators", tags: ["favicon", "icon", "generate", "design"],
    href: "/tools/favicon-generator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "screen-resolution-tester", name: "Screen Resolution Tester",
    summary: "See your current screen dimensions, pixel ratio and responsive breakpoints.",
    category: "developer", tags: ["screen", "resolution", "responsive", "breakpoint", "test"],
    href: "/tools/screen-resolution-tester",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "text-binary-converter", name: "Text ↔ Binary Converter",
    summary: "Convert text to binary and binary back to text, one click away.",
    category: "developer", tags: ["text", "binary", "convert", "encode"],
    href: "/tools/text-binary-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "date-format-converter", name: "Date Format Converter",
    summary: "Convert any date to ISO, Unix timestamp, locale, RFC 2822 and more formats.",
    category: "utilities", tags: ["date", "format", "convert", "timestamp", "iso"],
    href: "/tools/date-format-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "password-strength-checker", name: "Password Strength Checker",
    summary: "Analyze password strength with entropy, criteria checks and a quality score.",
    category: "security", tags: ["password", "strength", "security", "entropy"],
    href: "/tools/password-strength-checker",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "wcag-contrast-checker", name: "WCAG Contrast Checker",
    summary: "Check color-pair contrast against WCAG AA and AAA accessibility standards.",
    category: "developer", tags: ["wcag", "contrast", "accessibility", "color", "a11y"],
    href: "/tools/wcag-contrast-checker",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "preferences" },
  },
  {
    kind: "text", slug: "json-minifier", name: "JSON Minifier",
    summary: "Compress JSON by removing all whitespace — see bytes saved instantly.",
    category: "developer", tags: ["json", "minify", "compress", "optimize"],
    href: "/tools/json-minifier",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "text", slug: "markdown-to-html-converter", name: "Markdown to HTML",
    summary: "Convert Markdown to HTML with headings, lists, links, code blocks and more.",
    category: "developer", tags: ["markdown", "html", "convert", "render"],
    href: "/tools/markdown-to-html-converter",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none" },
  },
  {
    kind: "calculator", slug: "color-blindness-simulator", name: "Color Blindness Simulator",
    summary: "See how images look with protanopia, deuteranopia, tritanopia or achromatopsia.",
    category: "developer", tags: ["color", "blindness", "accessibility", "simulate", "vision"],
    href: "/tools/color-blindness-simulator",
    capabilities: { processing: "on-device", requiresNetwork: false, persistence: "none", maxFileSizeMb: 50 },
  },
];

export const TOOLS: readonly ToolDefinition[] = [...conversionTools, ...utilityTools];

const TOOLS_BY_SLUG = new Map(TOOLS.map((tool) => [tool.slug, tool]));

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS_BY_SLUG.get(slug);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === category);
}

/** All tags in use, sorted, for building filter UI without hard-coding a list. */
export function getAllTags(): string[] {
  return Array.from(new Set(TOOLS.flatMap((tool) => tool.tags))).sort();
}
